### PR TITLE
WIP: auto-completion with jedi

### PR DESCRIPTION
**Pull request by ihnorton**
Might close 7.

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot @ihnorton for working on this! I've tried it on Windows and it is almost there!

There is a build error in (buildtree)\nlohmann_json\single_include\nlohmann\json.hpp on Windows (snprintf not found). Adding this fixes the issue:

```
#if defined(_MSC_VER) && _MSC_VER < 1900
#define snprintf _snprintf
#endif
```

Packaging was not correct on Windows (I've installed the created extension .zip and Jedi was not found).

Auto-complete only returns part of the completed word (pr->int; instead of pr->print), which makes the suggestions a bit more difficult to interpret..

I think the speed is acceptable and works well overall!

Would be nice to get inspection (Shift+Tab) working as well. Could Jedi be used for implementing that, too?

**Comment by ihnorton** [comment]
> Would be nice to get inspection (Shift+Tab) working as well. Could Jedi be used for implementing that, too?

We could use jedi to find the token we want to inspect, but there are a lot of details to handle:

https://github.com/ipython/ipython/blob/7e739614377a1503db127fafc36332913bbd7d94/IPython/core/oinspect.py#L698-L938

If I followed the call-chain correctly, that code can easily be used stand-alone, so we could either import with license attribution (👎 ), or add a dependency on IPython, and specifically import the pieces we need (use `pip --no-dependencies` and only manually add any dependency that is absolutely necessary).

I was thinking about requiring/using IPython for completion too, but when I looked through that code it seemed like it required a lot of context we don't have (especially an initialized IPy shell loop). Plus they are very close to using jedi basically as-is, except for IPython magics.

Otherwise, we will be reimplementing a lot of existing code if we want things to work like IPython (which would be ideal, IMHO, to the extent feasible).

**Comment by lassoan** [comment]
Inspection (and many other IPython features) are nice-to-have. If some of them are very easy to implement then it may make sense to implement them. For more complex ones, we may consider using IPython after we upgraded Slicer to use Python3 and so become binary compatible with standard pip packages.

So, probably inspection can wait.

Do you need any help with fixing the Windows build and packaging errors?

**Comment by jcfr** [comment]
Thanks for the help @ihnorton

**Comment by ihnorton** [comment]
> Do you need any help with fixing the Windows build and packaging errors?

If you have a windows build and don't mind to look at one or both, that would be great. I haven't checked packaging on mac yet, may be the same issue (path setup?). 

Otherwise, I'll look at those in a few days.

**Comment by ihnorton** [comment]
Sorry about the delay; I just added an install specification for the python packages directory, so now CPack includes them in the output (h/t Jc's SlicerRadiomics cmake again).

**Comment by lassoan** [comment]
Thank you @ihnorton. Is this ready for testing or merging?

**Comment by lassoan** [comment]
With two small changes (pushed to this branch), building and packaging works on Windows. Auto-complete works nicely!

There is only one minor annoying issue (should not block integration): auto-complete list shows incomplete symbol names (just the completed parts), which makes the information a bit harder to read (for example, _pr_ populates the suggestion list with _int_ and _operty_ instead of _print_ and _property_).

**Comment by ihnorton** [comment]
Thanks for testing, great that it is working well on windows now (and thanks for the import fix).

>  pr populates the suggestion list with int and operty instead of print and property

I think the calculation of offsets might be a little off, I will double-check.

**Comment by lassoan** [comment]
Apart from this small inconvenience, is this ready to be merged?

**Comment by ihnorton** [comment]
> is this ready to be merged?

I fixed the issue you mentioned above (a9d585d), and squashed the commit history a little bit. After playing with it a bit, I think it is usable enough to merge so people can start trying it.

After looking through the IPython code several times recenlty, there are *many* small details they take care of to make things nicer, so it will be good if we can eventually use as much code from there as possible, in order to avoid reinventing the wheel -- and give users a familiar experience.

**Comment by jcfr** [comment]
Thanks for the update and for working on this.

I am wondering if having a consistent "auto-completion" experience between Slicer interpreter and the notebook is relevant for the user.

Also from the maintainers perspective (us in that case) , we have an other auto-completion code to maintain and debug.

After giving it a try later tonight, I am be convinced otherwise :smile: 

> we can eventually use as much code from there as possible, in order to avoid reinventing the wheel -- and give users a familiar experience.

:+1:

**Comment by lassoan** [comment]
I'll merge this, as this works already and I think this is the last major limitation of the kernel. We can make any changes under the hood later - it won't impact users.

**Pull request merged**
